# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControllerUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 4, 1, 1, 1)
        self.Pulse_Length_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Pulse_Length_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Pulse_Length_lineEdit.setObjectName("Pulse_Length_lineEdit")
        self.gridLayout.addWidget(self.Pulse_Length_lineEdit, 5, 2, 1, 1)
        self.Pulse_Length_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Pulse_Length_Button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Pulse_Length_Button.setObjectName("Pulse_Length_Button")
        self.gridLayout.addWidget(self.Pulse_Length_Button, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        self.Pulse_Delay_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Pulse_Delay_Button.setObjectName("Pulse_Delay_Button")
        self.gridLayout.addWidget(self.Pulse_Delay_Button, 7, 3, 1, 1)
        self.Temperature_label = QtWidgets.QLabel(self.centralwidget)
        self.Temperature_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Temperature_label.setObjectName("Temperature_label")
        self.gridLayout.addWidget(self.Temperature_label, 9, 1, 1, 1)
        self.V2_Label = QtWidgets.QLabel(self.centralwidget)
        self.V2_Label.setMaximumSize(QtCore.QSize(100, 20))
        self.V2_Label.setObjectName("V2_Label")
        self.gridLayout.addWidget(self.V2_Label, 10, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.V3_Label = QtWidgets.QLabel(self.centralwidget)
        self.V3_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.V3_Label.setObjectName("V3_Label")
        self.gridLayout.addWidget(self.V3_Label, 11, 1, 1, 1)
        self.V1_Label = QtWidgets.QLabel(self.centralwidget)
        self.V1_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.V1_Label.setObjectName("V1_Label")
        self.gridLayout.addWidget(self.V1_Label, 10, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 1, 1, 1)
        self.V4_Label = QtWidgets.QLabel(self.centralwidget)
        self.V4_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.V4_Label.setObjectName("V4_Label")
        self.gridLayout.addWidget(self.V4_Label, 11, 2, 1, 1)
        self.Pulse_Delay_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Pulse_Delay_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Pulse_Delay_lineEdit.setObjectName("Pulse_Delay_lineEdit")
        self.gridLayout.addWidget(self.Pulse_Delay_lineEdit, 7, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 8, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ADC Acquire"))
        self.checkBox_3.setText(_translate("MainWindow", "Disable Differential Switching"))
        self.Pulse_Length_Button.setText(_translate("MainWindow", "Send"))
        self.label_5.setText(_translate("MainWindow", "Pulse Length (uS)"))
        self.checkBox.setText(_translate("MainWindow", "Enable 1"))
        self.Pulse_Delay_Button.setText(_translate("MainWindow", "Send"))
        self.Temperature_label.setText(_translate("MainWindow", "TextLabel"))
        self.V2_Label.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "DAC"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset I2C"))
        self.V3_Label.setText(_translate("MainWindow", "TextLabel"))
        self.V1_Label.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Pulse Delay (uS)"))
        self.V4_Label.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox_2.setText(_translate("MainWindow", "Enable 2"))
from pyqtgraph import PlotWidget
